version: "3.9"

services:
    shop_api:
        build: ./shop_api
        container_name: shop_api
        env_file:
            - ./.env
        ports:
            - 80:8080
        depends_on:
            - mongodb
            - postgres
        command: uvicorn --workers 1 --host 0.0.0.0 --port 8080 main:app

    mongodb:
        image: mongo:5.0
        restart: unless-stopped
        container_name: mongodb_shop
        expose:
            - 27017
        ports:
            - 27017:27017
        env_file:
            - ./.env
        volumes:
            - ./mongo/data/:/data/db

    postgres:
        image: postgres
        restart: unless-stopped
        container_name: postgres_shop
        expose:
            - 5432
        env_file:
            - ./.env
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
