version: "3.9"

services:
    shop_api:
        build: 
            context: ./shop_api
            tags:
                - shop_api:1
        container_name: shop_api
        labels:
            - com.host.description=label
        env_file:
            - ./.env
        ports:
            - 8000:8080
        depends_on:
            - mongodb
            - postgres
        command: uvicorn --workers 1 --host 0.0.0.0 --port 8080 main:app

    mongodb:
        image: mongo:5.0
        restart: unless-stopped
        container_name: mongodb_shop
        expose:
            - 27017
        env_file:
            - ./.env
        volumes:
            - mongo_data:/data/db

    postgres:
        image: postgres:15
        restart: unless-stopped
        container_name: postgres_shop
        expose:
            - 5432
        env_file:
            - ./.env
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
    mongo_data:
