version: "3.9"

services:
    mongodb:
        image: mongo:5.0
        restart: unless-stopped
        container_name: mongodb
        ports:
            - 27017:27017
        env_file:
            - ./.env
        volumes:
            - ./mongo/db/:/data/db
